version: "3.9"

services:
  django:
    build: ./project
    command: sh -c "python manage.py migrate && gunicorn Mega_Market_Open_API.wsgi:application --bind 0.0.0.0:8000 "
    volumes:
      - ./project:/project
      - static_volume:/home/ubuntu/project/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=yndx_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  nginx:
          build: ./nginx
          depends_on:
            - django
          ports:
            - "80:80"
          volumes:
            - static_volume:/home/ubuntu/project/staticfiles      
volumes:
  pg_data:
  static_volume:
           
