# Generated by Django 4.0.5 on 2022-06-20 12:49

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('O', 'OFFER'), ('C', 'CATEGORY')], max_length=1)),
                ('price', models.IntegerField(null=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parentId', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='mega_market.shopunit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
