# Generated by Django 4.0.5 on 2022-06-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mega_market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogsShopUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.UUIDField()),
                ('name', models.TextField()),
                ('date', models.DateTimeField()),
                ('parentId', models.UUIDField(blank=True, null=True)),
                ('type', models.CharField(choices=[('O', 'OFFER'), ('C', 'CATEGORY')], max_length=1)),
                ('price', models.IntegerField(null=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
