# Generated by Django 4.0.5 on 2022-06-29 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mega_market', '0002_logsshopunit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logsshopunit',
            name='level',
        ),
        migrations.RemoveField(
            model_name='logsshopunit',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='logsshopunit',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='logsshopunit',
            name='tree_id',
        ),
    ]
